### ISSUE TITLE
Add ability to add untracked files in branch-commit

### ISSUE THREAD

**Issue by abatilo** [aviator-co/av#129]
Right now, I can only automatically add modified files when I create a new
branch-commit. If I only have new files, `branch-commit` fails with the
following output.

```
⇒  av stack branch-commit -a -m "Base terraform structure"
On branch base-terraform-structure
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        terraform/

nothing added to commit but untracked files present (use "git add" to track)

Failed to create commit.
  - Cleaning up branch base-terraform-structure because commit was not successful.
```

I'm using version `v0.0.15`:
```
⇒  av version
v0.0.15
```

**Comment by travigd** [comment]
This is maybe a bit more interesting that it seems on first glance.

The `-a` (which I think should actually be `-A` but oh well) just passes through to the `git commit` command that we run as `--all`. But `--all` is defined as:
> Update the index not only where the working tree has a file matching <pathspec> but also where the index already has an entry. This adds, modifies, and removes index entries to match the working tree.
> -- https://git-scm.com/docs/git-add#Documentation/git-add.txt---all

Implicit in that is that Git actually won't stage untracked/new files. I personally think that's the wrong behavior, but that wasn't my decision. 😅

I generally try to bias more towards staying true to the behavior of Git to avoid an "uncanny valley" effect. That being said, I think there are two options here:
* Redefine `--all` in `av stack branch-commit` to be equivalent to `git add -A && git commit ...` (as opposed to the current `git commit -A ...`).
  * I think this is more inline with what people expect, but is different from `git commit`.
* Add support for a `<pathspec>` argument to `av stack branch-commit` (which TIL that `git commit` also supports).
  * This would mean you could do `av stack branch-commit <branchname> .` to commit everything in the working tree (assuming you're running it from the root of the repo).

Would the latter option work for you? We should probably add it anyway to have closer parity to `git commit`.

**Comment by travigd** [comment]
Okay, the above is actually incorrect(ish). @draftcode pointed out to me that I confused `git add --all` and `git commit --all`.

* `git commit` has `-a`/`--all` which does not add new files to the index.
* `git add` has `-A`/`--all` which does add new files to the index.

I think the solution we arrived at in our short chat was:
* Make `av stack bc -a` work like `git commit -a` (i.e., don't add new files to the index).
* Make `av stack bc -A` and `av stack bc --all` work like `git add -A` (i.e., add new files to the index).

**Comment by abatilo** [comment]
Oh FML. I ALSO forgot that there's a difference between commit and add all.

Thanks for digging into this. You did what I actually want even when I was just wrong
