### ISSUE TITLE
Allow syncing from a trunk branch

### ISSUE THREAD

**Issue by draftcode** [aviator-co/av#132]
The idea is that when running `av stack sync` from `main`, sync all stacks that are rooted to `main`.

**Comment by travigd** [comment]
I'd prefer just having `av stack sync --all` to be more explicit (I can imagine someone accidentally running `av stack sync` on `main` when they expected to be on a feature branch and then being surprised when it starts asking them to resolve conflicts for other branches). But definitely open to other options if people have opinions! 😸

**Comment by draftcode** [comment]
OK. If you're OK with `--all`, I actually want to go with that direction. The only reason I took this sync from a trunk was that I thought you didn't like it.

**Comment by travigd** [comment]
Fixed by #134 !
