### ISSUE TITLE
Feature request: more branch editing workflows

### ISSUE THREAD

**Issue by abatilo** [aviator-co/av#171]
In a perfect world, I'd love to be able to do exactly what a `git rebase -i` does, but with branches. The ability to drop branches, fixup branches, squash branches, reorder branches, etc.

I find myself in situations where I have:
commit A
commit B
commit C <-- this commit makes atomic changes to something in commit A that would NOT impact any of the changes in commit B. I'd like an easy way for me to actually just fixup the changes in commit C directly into commit A and eliminate the branch representing that commit entirely.

**Comment by travigd** [comment]
Thanks for this use case, @abatilo!

We're working on a `git rebase -i` equivalent right now actually! Latest progress is #167 (it's not ready for general use, but you can at least see from the pull request description the high level interface).

In the case you describe above, I think it would look something like
```
# Original state
stack-branch A --trunk main
pick A1

stack-branch B
pick B1

stack-branch C
pick C1


# Modify to
stack-branch A --trunk main
pick A1
pick C1  # move C1 to branch A; we'll also support squashing the commit too at some point

stack-branch B
pick B1
```

Will let you know when the features ready for use! Would what I described above solve your use case? Let me know if you have any thoughts.

**Comment by abatilo** [comment]
That looks exactly perfect @travigd!

Thank you

**Comment by travigd** [comment]
This was added! We forgot to release it publicly (whoops! 🙈) but it was pushed out in https://github.com/aviator-co/av/releases/tag/0.0.21.

**Comment by samuelhwilliams** [comment]
Nice that this exists. I use fixup commits fairly frequently and one of the things I wanted to be able to do in this is squash fixup commits. I can't see that this is currently possible with the `av` CLI. Is that functionality supported or on the roadmap (happy to make a new issue if not 👀)?

**Comment by jainankit** [comment]
Hi @samuelhwilliams you can use `av commit --amend` to amend changes to existing commit. I believe we don't have a way to squash multiple commits together. Feel free to file a new issue for it

**Comment by jainankit** [comment]
Just for clarification, this particular ticket is related to reordering commits, that is supported via `av reorder`
https://docs.aviator.co/aviator-cli/how-to-guides/split-and-fold-pull-requests
