### ISSUE TITLE
baseurl not working

### ISSUE THREAD

**Issue by ryanking** [aviator-co/av#215]
AFAICT, the github baseurl config parameter described [here](https://docs.aviator.co/aviator-cli/configuration) does not work.

I am testing with an on-prem hosted github enterprise and `av` appears to be trying to connect to github.com still. If I set `baseUrl` to a non-sensical domain (literally, `example.com`), I get an auth error, rather than something related to DNS.

[The code to create a new client](https://github.com/aviator-co/av/blob/52bd6df7edaa26e69bcaec03e79c2dc85ac1f8d6/cmd/av/main.go#L178) does not seem to pass the baseUrl field to the constructor.

**Comment by travigd** [comment]
Hey @ryanking -- thanks for reporting!

Do you think you can try testing with #216? I don't have a GHES instance to test with.

**Comment by ryanking** [comment]
@travigd running that branch has gotten me to the point where it is contacting the right host (if I put a bogus host name in, I get a tcp dial error).

However, when I run `av auth status` it says I am not logged in. I suspect there is an issue [like this one](https://github.com/google/go-github/issues/958), but not sure.

**Comment by ryanking** [comment]
Perhaps not, I see that you are adding `/api/graphql` to the param.

As another data point, this command works for me–

```
curl -i -H 'Content-Type: application/json' -H "Authorization: bearer $TOKEN" $BASEURL/api/graphql
```

Where TOKEN and BASEURL are the same settings I have in ~/.av/config.yaml.

Meanwhile:

```
$ av auth status
error: You are not logged in. Please verify that your API token is correct.
```

**Comment by travigd** [comment]
`av auth status` is only concerned with authentication to the Aviator API. You'll need to separately set `aviator.apiHost` and `aviator.apiToken` to make that work as expected.

But at this point, `av pr create` should work as expected even without setting your Aviator credentials.

**Comment by travigd** [comment]
Ope looks like GitHub auto-closed this issue. @ryanking let me know if you're still having issues. I also opened #217 to improve the confusing UX around `av auth status`.

**Comment by travigd** [comment]
Yep, meant to release this the other day, sorry for the delay! https://github.com/aviator-co/av/releases/tag/v0.0.29
