### ISSUE TITLE
Look for PR template in root directory

### ISSUE THREAD

**Issue by andrewwdye** [aviator-co/av#219]
## Problem
I've started using `av`, and it doesn't seem to be picking up my PR template. Looks like [this logic](https://github.com/aviator-co/av/blob/49a7f5b82a98b014d31ec31827cb285518c7b023/internal/actions/pr.go#L463-L467) only looks in the `.github/` directory.

[Looks like](https://github.com/aviator-co/av/blob/49a7f5b82a98b014d31ec31827cb285518c7b023/internal/actions/pr.go#L463-L467) `.`, `.github/` and `docs/` are the commonly supported locations.

## Repro
Verify template exists
```
❯ ls pull_request_template.md
pull_request_template.md
```

Create a pr
```
❯ av pr create --draft --edit
```

**Comment by jainankit** [comment]
Hi @andrewwdye , can you confirm that this file is located in `.github/` directory on the root level in your repository?
I just tested this and it works when the file was at:
```
.github/PULL_REQUEST_TEMPLATE.md
```

**Comment by andrewwdye** [comment]
Ah, I misread the logic earlier as checking both root and `.github/` dirs. We keep ours at the root, which looks to be one of the [common patterns](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template).

**Comment by jainankit** [comment]
Oh I see, let's keep this issue open and we will add a patch to support root directory. Meanwhile, perhaps you can move the file to `.github/`?

**Comment by andrewwdye** [comment]
Thanks! Update the issue description accordingly. Happy to put up a PR as well if you take contributions.

**Comment by jainankit** [comment]
Absolutely! Thanks @andrewwdye !!
