### ISSUE TITLE
Configure a prefix for auto branch naming

### ISSUE THREAD

**Issue by abatilo** [aviator-co/av#227]
When an `av stack bc` does NOT specify a branch name, a name is automatically generated based on the message name.

I'm looking to be able to set a global prefix on this, as its been common for me to work at places where you prefix your branch names with your own name to avoid accidental collisions on branch names.

**Comment by jainankit** [comment]
Hi @abatilo , this is cool idea. Thanks for the suggestion.

**Comment by jainankit** [comment]
Hi @abatilo , this is now generally available in the new release: https://github.com/aviator-co/av/releases/tag/v0.0.31
