### ISSUE TITLE
Add comment to each PR displaying position in stack

### ISSUE THREAD

**Issue by mattd-tg** [aviator-co/av#228]
Similar to `ghstack` or `spr` or `graphite`, it is hard to keep track of what is going on if there isn't a comment on each PR showing the relationship of each PR in the stack and the order in which they reside.

Something like this for illustration:

![image](https://github.com/aviator-co/av/assets/132939725/9335fb05-0424-47a6-954f-729581e3294e)

**Comment by jainankit** [comment]
Hey @mattd-tg thanks for reporting this issue. That specific functionality works  as after you create an account and configure [Aviator API token](https://docs.aviator.co/aviator-cli/how-to-guides/create-a-user-access-token).

See for instance:
https://github.com/jain-av/mq-demo/pull/1890

**Comment by mattd-tg** [comment]
Ah I see, didn't have the token set up. Thanks!
