### ISSUE TITLE
Use Github Pull Request Template

### ISSUE THREAD

**Issue by mattd-tg** [aviator-co/av#229]
It would be really cool if the editor used the repo defined pull request template when submitting a PR/stack

**Comment by jainankit** [comment]
This is already supported. It should pick up the GitHub's template if defined in one of the following paths:
- `./PULL_REQUEST_TEMPLATE.md`
- `./.github/PULL_REQUEST_TEMPLATE.md`
- `./docs/PULL_REQUEST_TEMPLATE.md`

Both `PULL_REQUEST_TEMPLATE.md` and `pull_request_template.md` are supported. Can you check where your template file is located?

**Comment by mattd-tg** [comment]
Ah okay, do you need the aviator token set up for it to work?

**Comment by jainankit** [comment]
No, not this one.

**Comment by mattd-tg** [comment]
Awesome, it works when I moved it to one of those spots. Thanks!
