### ISSUE TITLE
set upstream when creating new branches

### ISSUE THREAD

**Issue by raylu** [aviator-co/av#234]
`av stack submit` pushes branches, creating them on the remote if they don't exist
however, it does so without `--set-upstream`

our github repo is configured to delete branches automatically when PRs close. I want to delete my local copy of the branch when that happens, so I wrote a script to prune my local branches. it differentiates between branches I haven't yet pushed at all vs branches that have been merged and deleted on the remote by checking if the local branch has an upstream set

#88 says
> This should not affect most of the users. Most of them won't notice the change. The only case they are affected is
> (1) They do not use `av pr create` but use `av stack sync` by some means creating a branch metadata and
> (2) set the upstream branch to a different name manually

this affects me because I don't use `av pr create`. although I don't pick a different name upstream, my branch pruning script relies on the presence of the config

> in order for a user to be affected by this change, they somehow need to get around it to use the "upstream" strategy

it turns out I also use `push.default = upstream`

---

I think the three options here are
1. add a config for whether to set upstream whenever `av` pushes a branch
2. check whether the branch has a remote by the same name and only set upstream if it doesn't. this strikes me as a very weird solution because the actual thing you should check is... the upstream (and the `push.default` setting). it would automatically support both @draftcode and my use-cases, though
3. just revert 949593a270d4. while this would break draftcode's use-case, it does seem much more standard then setting the upstream to the trunk branch

**Comment by draftcode** [comment]
Talked with @raylu offline.

To summarize, raylu has a script that uses the branch's upstream config (`branch.<name>.merge` described in `man 1 git-config`), as a proxy to tell if a branch is pushed to some branch or not. The git-push strategy part is not that relevant, as this is anyway used as a way to check that part.

As a resolution, when a branch is pushed to remote, we can update `av` to set `branch.<name>.av-pushed-ref` (and probably `branch.<name>.av-pushed-remote`) to indicate which ref and remote `av` has pushed.
