### ISSUE TITLE
av st sync when on trunk branch

### ISSUE THREAD

**Issue by oleg-codaio** [aviator-co/av#363]
I found a few smaller issues with the sync workflow when currently on the trunk branch (`main` for me in my repo).

If I'm on my `main` branch and run `av st sync`, I get an error: `error: current branch is not adopted to av`.

If I run `av st adopt`, it hangs.

If I run `av st sync --all`, things mostly work, but `av` also attempts to force-push the trunk branch, which results in an error: `Pushing to main directly is not allowed.` because the trunk branch is protected on GitHub.

**Comment by draftcode** [comment]
https://github.com/aviator-co/av/issues/386 for the `main` being pushed problem

**Comment by draftcode** [comment]
v0.0.40 should include the fixes mentioned above. `main` being pushed one, please give us details if you have a reproducible setup on the issue link mentioned above. Closing this.
