### ISSUE TITLE
Is there a reason that local branches do not have their upstream tracking branch set?

### ISSUE THREAD

**Issue by kylebjordahl** [aviator-co/av#437]
One pain point I am experiencing is that branches created by the CLI do not have their upstreams set once they are submitted to the remote. Though this does not cause issues when interacting solely through the CLI, other tools which use git context suffer when this is not set. One such example is the VS Code GitHub extension, which does not identify the branch as having an associated PR due to the missing upstream, thus failing to display inline comments and other useful features of the extension.

So, I guess I'm asking: "is the lack of an upstream on my local branches an intended thing, or is this a bug?"

**Comment by draftcode** [comment]
`av` doesn't do anything around the upstream configuration (https://github.com/aviator-co/av/blob/37c9124ae66400b021f513ea95b331fe1e78046b/internal/actions/pr.go#L201). So I was hoping that `push.autoSetupRemote` is honored, but it's not the case?

**Comment by kylebjordahl** [comment]
I'll check my local configuration and see if I can sort it out from there; thanks for the quick reply @draftcode!

**Comment by kylebjordahl** [comment]
I thought it wasn't working, but turns out our devcontainer is on an older version of git! I'm suspecting that's the culprit here, as we don't have `push.autoSetupRemote` support in the first place (I suspect I was getting that behavior because I was pushing using the VSCode built in UI button, and it probably solved for that without me realizing)
