### ISSUE TITLE
Add link to various PRs in the stack in the description

### ISSUE THREAD

**Issue by msmanek-dd** [aviator-co/av#439]
Hi! I'm really loving using av in my day to day work. Thank you for making it! One thing that would make it much easier for reviewers is for them to be able to quickly link between the different PRs in a stack. So, is it possible to link the various items in a stack in the PR description?

ex:

# Description
Some summary of changes
## Stack
Link to bottom PR : Stack Item 1 Title

Link to prev PR : Stack Item 2 Title

Stack Item 3 Title (THIS PR)

Link to next PR : Stack Item 4 Title

**Comment by jainankit** [comment]
Hi @msmanek-dd thanks for reporting the issue. This should already be possible with a config:
```
pullRequest:
  writeStack: true
```

Reference: https://docs.aviator.co/aviator-cli/configuration

Let me know if that doesn't work.

**Comment by msmanek-dd** [comment]
this indeed does work and is AWESOME! Thank you! I've added the flag in my config and it works wonderfully!

Two recommendations:
1. Make this the default
2. Update the docs to surface this more obviously :)
