### ISSUE TITLE
av stack tree doesn't show "which" master a stack stems from

### ISSUE THREAD

**Issue by Kimeiga** [aviator-co/av#443]
![image](https://github.com/user-attachments/assets/695538f0-393f-47e5-8e34-17b1a8e222ba)

one thing i noticed is that av stack sync --rebase-to-trunk doesn't update all the stacks only the current one, but when you av stack tree, it doesn't show the older versions of master that other stacks are based on . So there's really no way of knowing which stacks are up to date with latest master or not

pictured is `g j` my alias for `git branchless sl` which shows the full unsimplified tree of commits

**Comment by jainankit** [comment]
Yes, stack sync updates the current stack by default. To sync all stacks, you can use `av stack sync --all`.
