### ISSUE TITLE
Integrating with On Prem Aviator Instances

### ISSUE THREAD

**Issue by msmanek-dd** [aviator-co/av#444]
Hi!

I have an on prem installation of Aviator. When trying to integrate with it to land PRs with the cli, I get the following error:

```
error: failed to queue pull request: Post "https://api.aviator.prod.build.doordash.red/graphql": tls: failed to verify certificate: x509: certificate is valid for *.prod.build.doordash.red, not api.aviator.prod.build.doordash.red
```

in my settings, I have the following as the `apiHost` -> `https://api.aviator.prod.build.doordash.red`

How do I fix this?

**Comment by jainankit** [comment]
> Hi!
> 
> I have an on prem installation of Aviator. When trying to integrate with it to land PRs with the cli, I get the following error:
> 
> ```
> error: failed to queue pull request: Post "https://api.aviator.prod.build.doordash.red/graphql": tls: failed to verify certificate: x509: certificate is valid for *.prod.build.doordash.red, not api.aviator.prod.build.doordash.red
> ```
> 
> in my settings, I have the following as the `apiHost` -> `https://api.aviator.prod.build.doordash.red`
> 
> How do I fix this?

I think the apiHost for self-hosted github is typically: `https://<hostname>/api/v3`, so in your case that should be:
`https://aviator.prod.build.doordash.red/api/v3`

**Comment by msmanek-dd** [comment]
thanks for the quick reply @jainankit 

So, I changed the apiHost to `https://aviator.prod.build.doordash.red/api/v3`

```
(base) m.manek@H9JX16XVCT av % av auth status --debug
DEBU[0000] enabled debug logging                         av_version=v0.0.43
DEBU[0000] unable to load Git repo (probably not inside a repo)  error="failed to find git directory (are you running inside a Git repo?): exit status 128"
DEBU[0000] loaded config file                            config_file=/Users/m.manek/.config/av/config.yaml
DEBU[0000] loaded config file                            config_file=config.yaml
DEBU[0000] creating GraphQL client                       api_url="https://aviator.prod.build.doordash.red/api/v3/graphql"
non-200 OK status code: 404 NOT FOUND body: "Page not found"
DEBU[0000] executing GitHub API query...                 variables="map[string]interface {}(nil)"
DEBU[0000] GitHub API query succeeded                    elapsed=183.31925ms result="&struct { Viewer gh.Viewer \"graphql:\\\"viewer\\\"\" }{Viewer:gh.Viewer{Name:\"MohammedShabbar Manek\", Login:\"msmanek-dd\"}}" variables="map[string]interface {}(nil)"
Logged in to GitHub as MohammedShabbar Manek (msmanek-dd).
DEBU[0000] command exited                                duration=683.035583ms
DEBU[0000] fetched latest released version               latest=v0.0.43
```

Seems to 404. I think the cli automatically appends `/graphql`. Maybe this is a bug?

**Comment by jainankit** [comment]
Ohh that's right, I confused the github url with aviator url. You just need your standard web url for the apiHost: `https://aviator.prod.build.doordash.red`

**Comment by msmanek-dd** [comment]
ooo awesome! this works, thank you :)
