### ISSUE TITLE
Add ability to queue a stack from the cli

### ISSUE THREAD

**Issue by msmanek-dd** [aviator-co/av#450]
(unless I'm just unaware of the command, but it seems like `av pr queue` does not have any options for that. If it is there, pls document lol)

**Comment by jainankit** [comment]
> (unless I'm just unaware of the command, but it seems like `av pr queue` does not have any options for that. If it is there, pls document lol)
I'm not sure I follow what you are suggesting. To queue the stack PRs via the CLI, you checkout the branch at the top of the stack (or partial stack) that you want to queue, run `av pr queue`. What are you trying to do that's not working?

**Comment by msmanek-dd** [comment]
oh yes, that actually works. my mistake, this was a dumb issue :(
