### ISSUE TITLE
Can't upgrade av via homebrew

### ISSUE THREAD

**Issue by dpashk-figma** [aviator-co/av#469]
Looks like you recently released a new version, and I keep getting this message every time I use an `av` command:

```
>> A new version of av is available: v0.0.43 => v0.0.46
>> https://docs.aviator.co/reference/aviator-cli/installation#upgrade
```

However, when I try to follow the [Homebrew upgrade instructions](https://docs.aviator.co/aviator-cli/installation#homebrew), the new version isn't there:

```
% brew upgrade av
Warning: aviator-co/tap/av 0.0.43 already installed
```

**Comment by draftcode** [comment]
You might want to run `brew update` first to update the list of packages?

**Comment by dpashk-figma** [comment]
Rookie mistake, that was it! Sorry for the trouble. You might want to update the docs though.

**Comment by tulioz** [comment]
Good call out, I've updated the docs. Rolling out README update as part of some larger changes too.
