### ISSUE TITLE
`av tidy` removes branch metadata for branches stacked more than one away from the root

### ISSUE THREAD

**Issue by steve-codaio** [aviator-co/av#486]
`av tidy` deletes branches from the av database without logging anything. Have a two branch stack, like so
```
$ av tree

  * branch-two (HEAD)
  │ No pull request  
  │                  
  * branch-one       
  │ No pull request  
  │                  
  * main             
```

Then run `av tidy`

```
$ av tidy

  ✓ No branch to tidy
```                
Now run tree again
```
$ av tree     

  * branch-one     
  │ No pull request
  │                
  * main                         
```

At this point the branch is gone from .git/av/av.db. The branch itself is still there and hasn't been touched, so you can recover by running `av adopt` (and then `av sync` if it had a PR associated with it)

**Comment by tulioz** [comment]
Thanks for the report! Found the root cause, will push out the fix tomorrow.
