### ISSUE TITLE
Feature request: disable opening browser to PR with `av stack submit`

### ISSUE THREAD

**Issue by abatilo** [aviator-co/av#84]
If I have several stacked branches, I'd like to be able to pass a flag to `av stack submit` so that it doesn't open a tab to each PR for every single branch.

**Comment by travigd** [comment]
We might want to revisit whether the functionality of opening the browser by default. We can just print a link and most terminals these days will linkify it.

In the mean time, you can disable this functionality by setting `pullRequest.openBrowser` to `false` in the config file: https://docs.aviator.co/reference/aviator-cli/configuration.
